import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();

const draftGenerator = readFileSync(join(root, "src/features/nutrition/draft-generator.ts"), "utf8");
assert.match(draftGenerator, /day_by_day_training_aware_analysis/, "weekly generator must include day-by-day methodology guardrail");
assert.match(draftGenerator, /detailed_day_level_athlete_draft/, "weekly generator must require detailed day-level athlete draft");
assert.match(draftGenerator, /detectNutritionMacroReviewWeekMismatch/, "daily facts builder must detect macro/review week mismatch");
assert.match(draftGenerator, /date_range_mismatch_detected/, "daily facts builder must annotate source quality on date mismatch");
assert.match(draftGenerator, /facts_only_no_recalculation/, "weekly generator must enforce no recalculation guardrail");
assert.match(draftGenerator, /athlete_message_draft должен включать 3-7 дневных наблюдений/i, "AI prompt must require day-level athlete draft");
assert.match(draftGenerator, /no_hallucinated_workouts_or_gels/, "weekly generator must ban workout/fueling hallucinations");
assert.match(draftGenerator, /carb_reference_not_prescriptive/, "weekly generator must keep carb band non-prescriptive");
assert.match(draftGenerator, /small_step_progression_if_low_carbs/, "weekly generator must enforce gradual progression");
assert.match(draftGenerator, /no_english/, "weekly generator must enforce russian-only draft");
assert.match(draftGenerator, /weekday_ru/, "day-by-day should use weekday_ru");
assert.match(draftGenerator, /date_label/, "day-by-day should use date_label");
assert.match(draftGenerator, /training_label/, "day-by-day should use training_label");
assert.match(draftGenerator, /hint_for_comment/, "day-by-day should use hint_for_comment");
assert.match(draftGenerator, /комментируй только дневные totals[;,]\s*без intraday/i, "prompt must ban intra-day detail in day-by-day section");
assert.match(draftGenerator, /source_quality\.confidence=low/i, "prompt must include low-confidence caution rule");
assert.match(draftGenerator, /Строгая формальность: только ты ИЛИ только вы/i, "prompt must enforce formality consistency");
assert.match(draftGenerator, /Запрещено(?:\s+в athlete_message_draft)?:\s*\*\*, ---, code fences/i, "prompt must enforce plain text");
assert.match(draftGenerator, /(?:Разрешённая )?[Пп]ричинность только с хеджами/i, "prompt must enforce hedged causality");
assert.doesNotMatch(draftGenerator, /classify days|day classification rules/i, "prompt must not ask model to classify days");
assert.doesNotMatch(draftGenerator, /compute formulas|calculate formulas/i, "prompt must not ask model to calculate formulas");
assert.match(draftGenerator, /one_focus/, "weekly generator output must contain one_focus");
assert.match(draftGenerator, /daily_analysis/, "weekly generator output must contain daily_analysis");
assert.match(draftGenerator, /canonical_daily_analysis/, "weekly generator output must contain canonical_daily_analysis");
assert.match(draftGenerator, /weekday_ru/, "weekly generator output must include weekday_ru");
assert.match(draftGenerator, /training_type/, "weekly generator output must include training_type");
assert.match(draftGenerator, /training_label/, "weekly generator output must include training_label");
assert.match(draftGenerator, /hint_for_comment/, "weekly generator output must include hint_for_comment");
assert.match(draftGenerator, /source_quality/, "weekly generator output must include source_quality");
assert.match(draftGenerator, /training_nutrition_links/, "weekly generator output must contain training_nutrition_links");
assert.match(draftGenerator, /bodyweight_kg/, "weekly generator output must contain bodyweight_kg");
assert.match(draftGenerator, /carb_progression_strategy/, "weekly generator output must contain carb_progression_strategy");
assert.match(draftGenerator, /coach_context_ru/, "weekly generator must include coach_context_ru in facts payload");
assert.match(draftGenerator, /athlete_report_signals/, "weekly generator must include athlete_report_signals in facts payload");
assert.match(draftGenerator, /interpretation_shadow/, "weekly generator must persist interpretation shadow metadata");
assert.match(draftGenerator, /generateNutritionWeeklyInterpretationShadow/, "weekly generator must call shadow interpretation generator");
assert.match(draftGenerator, /nutrition_goal/, "weekly generator must include nutrition_goal in facts payload");
assert.match(draftGenerator, /coach_memory/, "weekly generator must include coach memory summaries in facts payload");
assert.match(draftGenerator, /athlete_report_signals_require_coach_review/, "weekly generator must flag illness/cycle/injury signals");
assert.match(draftGenerator, /coach_summary_text/, "weekly generator must include coach_summary_text");
assert.match(draftGenerator, /day_by_day_analysis_text/, "weekly generator must include day_by_day_analysis_text");
assert.match(draftGenerator, /generation_mode/, "weekly generator must include generation_mode");
assert.match(draftGenerator, /prompt_version/, "weekly generator must include prompt_version");
assert.match(draftGenerator, /generateNutritionWeeklyReviewNarrative/, "weekly generator must include AI narrative layer");
assert.match(draftGenerator, /nutrition-weekly-review-v3-ai/, "weekly generator must use v3 prompt version");
assert.match(draftGenerator, /Return strict JSON only/, "AI prompt must require strict JSON output");
assert.match(draftGenerator, /не пересчитывай и не придумывай:.*г\/кг/i, "AI prompt must ban strict g/kg targets for athlete text");
assert.doesNotMatch(draftGenerator, /Главный фокус недели — главный фокус/i, "generator should avoid duplicated focus template");
assert.doesNotMatch(draftGenerator, /день самой работы/i, "generator should avoid robotic phrase 'день самой работы'");

const studentPage = readFileSync(join(root, "src/app/admin/coach-os/nutrition/[studentId]/page.tsx"), "utf8");
const draftCopyBlock = readFileSync(join(root, "src/app/admin/coach-os/nutrition/NutritionDraftCopyBlock.tsx"), "utf8");
const studentUi = `${studentPage}\n${draftCopyBlock}`;
assert.match(studentPage, /Главный вывод для тренера/, "UI should render coach summary section");
assert.match(studentPage, /Разбор по дням/, "UI should render day-by-day section");
assert.match(studentPage, /Связки тренировка ↔ питание/, "UI should render training links section");
assert.match(studentPage, /<details>/, "UI should collapse technical JSON");
assert.match(studentPage, /Вес не задан — расчёт г\/кг и белок достаточный недоступны\./, "UI should explain missing weight");
assert.match(studentPage, /Safety JSON/, "UI should keep raw safety JSON collapsed");
assert.doesNotMatch(studentPage, /JSON\.stringify\(card\.weeklyAnalysis\.nutritionSummary,\s*null,\s*2\)/, "raw JSON cannot be primary UI");
assert.match(studentUi, /Сгенерировано шаблоном, лучше проверить текст вручную\./, "UI should warn when fallback text is shown");
assert.match(studentPage, /Служебный черновик обзора из БД/, "UI should keep secondary review draft heading in advanced section");
assert.match(studentPage, /buildDerivedNutritionCoachDayByDayText/, "coach day-by-day section must use derived canonical facts");
assert.match(studentPage, /Исходный сохранённый разбор \(служебно\)/, "coach section must keep stored day-by-day as secondary details");
assert.match(studentPage, /Метрики недели/, "UI should keep metrics section");
assert.match(studentPage, /Контекст для разбора питания/, "UI should show coach context block");
assert.match(studentPage, /Сигналы из комментария ученика/, "UI should show athlete report signals section");

console.log("PASS check-nutrition-weekly-review-quality");
